name: realtime_chat
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  animations: ^2.0.11
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localization: ^0.3.0
  flutter_secure_storage: ^9.2.2
  get_it: ^8.0.3
  go_router: ^14.6.2
  image_picker: ^1.1.2
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.3.3
  socket_io_client: ^3.0.0
  url_launcher: ^6.3.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  js: ^0.6.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env
